apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spring-todo-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: arch.homework
    http: 
      paths:
        - path: /
          backend:
            serviceName: spring-todo-app-service
            servicePort: 9000